name: CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal