name: Publish

on:
  push:
    branches:
    - master
  
jobs:
  publish-nuget:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish to NuGet OrchardCore.Media.Amazon.S3
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/OrchardCore.Media.Amazon.S3/OrchardCore.Media.Amazon.S3.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
    - name: Publish to NuGet OrchardCore.FileStorage.Amazon.S3
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/OrchardCore.FileStorage.Amazon.S3/OrchardCore.FileStorage.Amazon.S3.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}