name: Publish

on:
  push:
    branches:
    - master
  
jobs:
  publish-nuget:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Install dependencies
      run: dotnet restore   
    - name: Build
      run: dotnet build --configuration Release

    - name: Publish to NuGet OrchardCore.Media.Amazon.S3
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/OrchardCore.Media.Amazon.S3/OrchardCore.Media.Amazon.S3.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
    - name: Publish to NuGet OrchardCore.FileStorage.Amazon.S3
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/OrchardCore.FileStorage.Amazon.S3/OrchardCore.FileStorage.Amazon.S3.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}